---
apiVersion: v1
kind: Service
metadata:
  name: codeheadnz-ltd-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
